AWSTemplateFormatVersion: '2010-09-09'
Description: 'AlcoLook - AWS Resources for Real-time Face Analysis (Privacy-First)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: alcolook
    Description: Project name for resource naming

Resources:
  # IAM Role for Rekognition (Real-time analysis only)
  RekognitionServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-rekognition-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: rekognition.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRekognitionReadOnlyAccess
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # IAM Role for Bedrock (AI Analysis)
  BedrockServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-bedrock-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Log Group (Anonymous analytics only)
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/alcolook/${Environment}'
      RetentionInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  RekognitionRoleArn:
    Description: ARN of the Rekognition service role
    Value: !GetAtt RekognitionServiceRole.Arn
    Export:
      Name: !Sub '${ProjectName}-rekognition-role-${Environment}'

  BedrockRoleArn:
    Description: ARN of the Bedrock service role
    Value: !GetAtt BedrockServiceRole.Arn
    Export:
      Name: !Sub '${ProjectName}-bedrock-role-${Environment}'

  LogGroupName:
    Description: Name of the CloudWatch log group
    Value: !Ref ApplicationLogGroup
    Export:
      Name: !Sub '${ProjectName}-log-group-${Environment}'
